[supervisord]
nodaemon=true

[program:job-expire-otp]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan schedule:work
autostart=true
autorestart=true
numprocs=3
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/otp_expire.log